### PR TITLE
New RMS proposal for systematic uncertainty

### PR DESCRIPTION
**Pull request by asculac**
This PR contains changes related to implementation of new proposal for using RMS method to calculate systematical part of uncertainty. See details in presentation [here](https://indico.cern.ch/event/1288547/contributions/5414376/attachments/2654622/4597206/26052023_RMS_EGamma.pdf)

Changes include:
- removal of alternative Tag variation which is only a cut variation
- adding an additional fit as combination of both alternative signal and background function applied at the same time (see **)
- Using mean value of SF as the central one and evaluation of the systematical part of the uncertainty as uncertainty on the mean RMS/sqrtN
- adding systematical part from alternative MC sample in cases where it is larger than the contribution from the statistical uncertainty from MC
- removed symmetrisation in eta (using the average value from eta+ and eta-) for the final uncertainty 

** in order to be able to use altSigBkg fit, settings file should be updated with fit parameters settings from [example](https://github.com/asculac/egm_tnp_analysis/blob/RMS_PR/etc/config/settings_UL2017_RMS_pt11_15.py#L156-L163)  

**NB!:**
Final egamma PDF is not fully correct yet, this should be investigated as the breakdown of the uncertainties shown in 2D histograms for the systematical contributions seems to be wrong. This is under investigation and any help with this will be much appreciated!

### CODE REVIEW

**Comment by Prasant1993** [comment]
Hi @asculac , I am starting to review your pull request. Thanks for all the work done.  I need a clarification here.
1) Tightening the tag cut should be a source of systematic. Why can't it be considered.
2) In the file : https://github.com/asculac/egm_tnp_analysis/blob/RMS_PR/libPython/efficiencyUtils.py#L35
While calculating the mean of the efficiency for all the uncertainty sources (AltBkgModel, AltSigModel, AltMCSignal, AltSigBkgModel), I see only three of them have been added. The "altMCsignal" has not been considered. Is it due to the "mean" of the efficiency we should consider separately from data and MC ?  If I understand correctly, we have one altMC here. The mean is nothing but the same.  But when you take the mean of the SF, you consider all the 5 (Nominal and all 4 systematics ) scale factors right ?  All the 5 scale factors I mentioned can come from the following ways : 
a) SF1 :  Nominal case (data eff from nominal fit/ nominal MC eff)
b) SF2 :  AltSigModel case ( data eff from altSig fit/ nominal MC eff)
c) SF3 :  AltBkgModel case (data eff from altBkg fit/ nominal MC eff)
d) SF4 : AltMCSignal case (data eff from nominal fit/ alt MC eff)
e) SF5 : AltSigBkgModel case ( data eff from altSigbkg fit/ nominal MC eff)

From your point of view, the data efficiency should be replaced by mean eff.  Is this how the mean SF have been calculated ?

**Comment by Prasant1993** [comment]
This part of the code is failing in the efficiency file : https://github.com/asculac/egm_tnp_analysis/blob/RMS_PR/libPython/efficiencyUtils.py#L370
in eta_1DGraph_list
    anError = effAverage.systCombined 
AttributeError: efficiency instance has no attribute 'systCombined'

After replacing this with effPlus and effMinus instead of effAverage, it is still failing.
in eta_1DGraph_list
    aValue  = (effPlus.mean + effMinus.mean)/2   #we use abs eta (average between etaplus and etaminus) for pt plot                                                
NameError: global name 'effPlus' is not defined

**Comment by asculac** [comment]
> Hi @asculac , I am starting to review your pull request. Thanks for all the work done. I need a clarification here.
> 
> 1. Tightening the tag cut should be a source of systematic. Why can't it be considered.
> 2. In the file : https://github.com/asculac/egm_tnp_analysis/blob/RMS_PR/libPython/efficiencyUtils.py#L35
>    While calculating the mean of the efficiency for all the uncertainty sources (AltBkgModel, AltSigModel, AltMCSignal, AltSigBkgModel), I see only three of them have been added. The "altMCsignal" has not been considered. Is it due to the "mean" of the efficiency we should consider separately from data and MC ?  If I understand correctly, we have one altMC here. The mean is nothing but the same.  But when you take the mean of the SF, you consider all the 5 (Nominal and all 4 systematics ) scale factors right ?  All the 5 scale factors I mentioned can come from the following ways :
>    a) SF1 :  Nominal case (data eff from nominal fit/ nominal MC eff)
>    b) SF2 :  AltSigModel case ( data eff from altSig fit/ nominal MC eff)
>    c) SF3 :  AltBkgModel case (data eff from altBkg fit/ nominal MC eff)
>    d) SF4 : AltMCSignal case (data eff from nominal fit/ alt MC eff)
>    e) SF5 : AltSigBkgModel case ( data eff from altSigbkg fit/ nominal MC eff)
> 
> From your point of view, the data efficiency should be replaced by mean eff. Is this how the mean SF have been calculated ?

Hi @Prasant1993 the "altMCsignal" is considered as a separated source of systematic and is added in quadrature later, in the cases when it is larger than statMC(#L77):
```
#don't include systMC when smaller than statMC
        if(systAltMC<self.errEffMC):
            systAltMC = 0
```
It is added in sum in quad in #L99  as self.syst[6]:  
```
self.systCombined = math.sqrt(self.systCombined*self.systCombined/4 + self.syst[6]*self.syst[6] + self.syst[0]*self.syst[0]+ self.syst[1]*self.syst[1]) #sum in quad with syst_altMC, statData and statMC
```

The mean SF value is the combination of 4 alternative measurements which are considered as equally valid (nom, altSig, altBkg and altSigBkg). AltMC *IS NOT* included here because it is a separated source of systematic and not part of the RMS estimate. 
This is done in #L36
```
self.mean=(effAltBkgModel+effAltSigModel+effAltSigBkgModel+effData)/4
```

**Comment by asculac** [comment]
> This part of the code is failing in the efficiency file : https://github.com/asculac/egm_tnp_analysis/blob/RMS_PR/libPython/efficiencyUtils.py#L370 in eta_1DGraph_list anError = effAverage.systCombined AttributeError: efficiency instance has no attribute 'systCombined'
> 
> After replacing this with effPlus and effMinus instead of effAverage, it is still failing. in eta_1DGraph_list aValue = (effPlus.mean + effMinus.mean)/2 #we use abs eta (average between etaplus and etaminus) for pt plot NameError: global name 'effPlus' is not defined

@Prasant1993 I am surprised to see that is failing, when I was testing it everything was running smoothly. I won't be able to check it this week, but I will take a look as soon as possible

**Pull request closed without merging**
